version: '3.8'

services:
  db:
    image: postgres:18-alpine
    container_name: duneflame-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=duneflame123
      - POSTGRES_DB=DuneFlameDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: duneflame-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@duneflame.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: